### ISSUE TITLE
RataDie calculation

### ISSUE THREAD

**Issue by gouniLee** [iLib-js/iLib#62]
*node v0.10*
`new Date(2019, 2, 31)`
`Sat Mar 30 2019 23:00:00 GMT-0100 (AZOT)`

*node v6.11*
`new Date(2019, 2, 31)`
`2019-03-31T01:00:00.000Z`

*latest version of chrome (62.0.3202.62)*
`new Date(2019, 2, 31)`
`Sun Mar 31 2019 01:00:00 GMT+0000 (AZOST)`

 result of 
     ***getTimeExtended()***
https://github.com/iLib-js/iLib/blob/development/js/lib/RataDie.js#L282
*node v0.10*  - **1553994000000**:Sun Mar 31 2019 01:00:00
> var value = new GregorianDate({year:2019, month:3, day:31, timezone:'local'})
undefined
> var date = DateFactory(value)
undefined
> date.getTimeExtended()
1553994000000

*node v6.11*  - **1553990400000** : Sat Mar 30 2019 23:00:00
> var value = new GregorianDate({year:2019, month:3, day:31, timezone:'local'})
undefined
> var date = DateFactory(value)
undefined
> date.getTimeExtended()
1553990400000

*latest version of chrome (62.0.3202.62)*  - **1553990400000** :Sat Mar 30 2019 23:00:00
> const myValue = new GregorianDate({year:2019, month:3, day:31, timezone:'local'})
> const myDate = DateFactory(myValue)
> console.log(myDate.getTimeExtended())
> 1553990400000

**Comment by Seonghyup** [comment]
I guess that iLib `RataDie` is based on old javascript engine.

**Comment by Seonghyup** [comment]
We need to fix this logic(https://github.com/iLib-js/iLib/blob/development/js/lib/GregorianDate.js#L160). 

    // if dst is defined, the intrinsic Date object has no way of specifying which version of a time you mean
    // in the overlap time at the end of DST. Do you mean the daylight 1:30am or the standard 1:30am? In this
    // case, use the ilib calculations below, which can distinguish between the two properly
    var d = new Date(this.year, this.month-1, this.day, this.hour, this.minute, this.second, this.millisecond);
    this.offset = -d.getTimezoneOffset() / 1440;

Maybe there was a change of the way to judge time(daylight/standard).

**Comment by gouniLee** [comment]
Closing this issue because it's fixed.
